apiVersion: v1
kind: Secret
metadata:
  name: crypto-dashboard-secrets
  namespace: crypto-dashboard
type: Opaque
stringData:
  JWT_SECRET: "CHANGE-ME-use-openssl-rand-base64-48"
  API_USER: "admin"
  API_PASS: "CHANGE-ME-strong-password"