cat *.ts >> data.txt
cat *.tsx >> data.txt
cat src/*.ts >> data.txt
echo "--------------------------------" >> data.txt
cat src/*.tsx >> data.txt
echo "--------------------------------" >> data.txt
cat src/pages/*.tsx >> data.txt
echo "--------------------------------" >> data.txt
cat src/components/*.tsx >> data.txt
echo "--------------------------------" >> data.txt
cat src/hooks/*.ts >> data.txt
echo "--------------------------------" >> data.txt
cat src/lib/*.ts >> data.txt
echo "--------------------------------" >> data.txt
cat src/lib/*.tsx >> data.txt
echo "--------------------------------" >> data.txt